# I. Data Analysis

***

In this notebook:
 1. Description of dataset
 2. Data analysis
 3. Preparation data for ML development

**Can be done by clicking "Run all"**

In [1]:
# Import libraries:
from pathlib import Path
import sys

project_root = Path.cwd().parent
sys.path.append(str(project_root / "scripts"))

import os
import pandas as pd
import numpy as np
from my_scripts import *

In [2]:
# Disable old API warring
import warnings 
warnings.filterwarnings('ignore', category=FutureWarning)

In [3]:
# Paths
path_to_data = '../data'
path_to_image = '../images'
path_to_table = '../tables'

In [4]:
# # Uncomment if Plotly is not displaying plots correctly (open interactive html-plots in browser).
# import plotly.io as pio
# pio.renderers.default = "browser"

***

## 1. Dataset description

In [5]:
# Open dataset file 'MX4_Dataset.csv'
dataset = pd.read_csv(os.path.join(path_to_data, 'MX4_Dataset.csv'), index_col=[0])
dataset.head(10)

,Refcode,DOI,Authors,Journal,Journal year,Journal volume,Journal page or number,Cation SMILES,Cation substructure SMILES,Space group,...,X...X contacts,VdW contacts,N_XX,N_VdW,XX_min,XX_average,VdW_average,Type of bandgap,Bandgap,Bangap estimation comments
0,AGODEI,10.1016/j.mencom.2018.09.012,"P.A.Buikin, A.B.Ilyukhin, A.E.Baranchikov, K.E...",Mendeleev Commun.,2018,28.0,490,[nH+]1c(N)cccc1,[nH+]1c(N)cccc1,Pbcn,...,3.9399 3.9399 3.9399 3.9399 4.4849 4.4849 4.48...,3.9399 3.9399 3.9399 3.9399,8.0,4.0,3.9399,4.2124,3.9399,direct,2.00,NaN
1,AGODIM,10.1016/j.mencom.2018.09.012,"P.A.Buikin, A.B.Ilyukhin, A.E.Baranchikov, K.E...",Mendeleev Commun.,2018,28.0,490,[nH+]1cc(N)ccc1,[nH+]1cc(N)ccc1,P21/c,...,3.9611 3.9611 4.1119 4.1119 4.1668 4.1668,3.9611 3.9611 4.1119 4.1119 4.1668 4.1668,6.0,6.0,3.9611,4.0799,4.0799,direct,2.07,NaN
2,AGODOS,10.1016/j.mencom.2018.09.012,"P.A.Buikin, A.B.Ilyukhin, A.E.Baranchikov, K.E...",Mendeleev Commun.,2018,28.0,490,[nH+]1ccc(N)cc1,[nH+]1ccc(N)cc1,Pbcn,...,3.9195 3.9195 3.9195 3.9195 4.477 4.477 4.477 ...,3.9195 3.9195 3.9195 3.9195,8.0,4.0,3.9195,4.1982,3.9195,direct,1.97,NaN
3,AGODOS01,10.1021/acs.inorgchem.9b01439,"Yue-Qiao Hu, Hong-Yan Hui, Wei-Quan Lin, Hong-...",Inorg.Chem.,2019,58.0,16346,[nH+]1ccc(N)cc1,[nH+]1ccc(N)cc1,Pbcn,...,3.9932 3.9932 3.9932 3.9932 4.5914 4.5914 4.59...,3.9932 3.9932 3.9932 3.9932,8.0,4.0,3.9932,4.2923,3.9932,direct,1.94,NaN
4,AGODOS02,10.1039/D3DT02910G,"G.Abdi, M.Gryl, A.Slawek, E.Kowalewska, T.Mazu...",Dalton Trans.,2023,52.0,14649,[nH+]1ccc(N)cc1,[nH+]1ccc(N)cc1,Pbcn,...,3.9123 3.9123 3.9123 3.9123 4.473 4.473 4.473 ...,3.9123 3.9123 3.9123 3.9123,8.0,4.0,3.9123,4.1927,3.9123,direct,1.91,NaN
5,AQALEM,10.1080/24701556.2021.1897137,"Jiahua Guo, Yuqi Zhang, Shouwen Jin, Xiaoyun Y...",Inorg.Nano-Metal Chem.,2021,NaN,1,c1ccccc1C[NH+](C)C,c1ccccc1C[NH+](C)C,Cc,...,4.0333 4.0333,NaN,2.0,0.0,4.0333,4.0333,4.0333,NaN,NaN,NaN
6,AYENEZ,10.1039/C6DT03602C,"A.J.Dennington, M.T.Weller",Dalton Trans.,2016,45.0,17974,[NH2+]1CC[NH2+]CC1,[NH2+]1CC[NH2+]CC1.O.O.O.O,P21/c,...,3.8001 3.8001 4.4371 4.4371 4.3383 4.3383,3.8001 3.8001,6.0,2.0,3.8001,4.1918,3.8001,direct,2.00,NaN
7,AYENEZ01,10.1039/C6DT03602C,"A.J.Dennington, M.T.Weller",Dalton Trans.,2016,45.0,17974,[NH2+]1CC[NH2+]CC1,[NH2+]1CC[NH2+]CC1.O.O.O.O,P21/c,...,3.7611 3.7611 4.3958 4.3958 4.2536 4.2536,3.7611 3.7611,6.0,2.0,3.7611,4.1368,3.7611,direct,2.00,NaN
8,AYENOJ,10.1039/C6DT03602C,"A.J.Dennington, M.T.Weller",Dalton Trans.,2016,45.0,17974,[NH+](C)1CC[NH2+]CC1,[NH+](C)1CC[NH2+]CC1.O.O.O,P21/c,...,3.8111 3.8111 4.3571 4.3571 4.2268 4.2268,3.8111 3.8111,6.0,2.0,3.8111,4.1317,3.8111,direct,1.95,NaN
9,AYENOJ01,10.1039/C6DT03602C,"A.J.Dennington, M.T.Weller",Dalton Trans.,2016,45.0,17974,[NH+](C)1CC[NH2+]CC1,[NH+](C)1CC[NH2+]CC1.O.O.O,P21/c,...,3.7647 3.7647 4.3237 4.3237 4.1693 4.1693,3.7647 3.7647 4.1693 4.1693,6.0,4.0,3.7647,4.0859,3.9670,direct,1.95,NaN

In each row there is one object corresponding one crystal structure of hybrid or all-inorganic group 15 metal halide with {MX<sub>4</sub>}<sup>–</sup> anion (M is metal: Bi<sup>3+</sup>, Sb<sup>3+</sup>; X is halogen: I<sup>–</sup>, Br<sup>–</sup>, Cl<sup>–</sup>).

Below information description contained in the columns:

* **Refcode** - crystallography database identifier (CSD, if the structure from ICSD or COD Refcode contain prefix “**ICSD_**” or “**COD_**”, respectively);

* **DOI**, **Authors**, **Journal**, **Journal year**, **Journal volume**, **Journal page or number** - information about publication in which the crystal structure is reported;

* **Cation SMILES** – SMILES representation of cation;

* **Cation substructure SMILES** – SMILES representation of cation substructure: cation including solvated and cocrystal molecules;

* **Space group**, **Int Tables number**, **Temperature**, **a**, **b**, **c**, **alpha**, **beta**, **gamma**, **V**, **Z**, **R factor** - crystallographic data about the crystal structure symmetry and the X-ray diffraction experiment;

* **MX4 type** - type of edge-shared $\{MX_{4}\}^{-}$ type: **alpha**, **beta**, **gamma**, (**See bellow I**), **no data** - *no structural data*;

* **M** - metal composition: **Bi**, **Sb** or **Bi Sb** for mixed compositions;

* **X** - halogen composition: **I**, **Br** or **Cl**, for mixed compositions – **Cl Br** or **Br I**;

* **X_t1**, **X_t2**, **X_d1**, **X_d2**, **X_d3**, **X_d4** - M–X distances labeled according to **II**, Å;

* **t1_t2**, **t1_d1**, **t1_d2**, **t1_d3**, **t1_d4**, **t2_d1**, **t2_d2**, **t2_d3**, **t2_d4**, **d1_d2**, **d1_d3**, **d1_d4**, **d2_d3**, **d2_d4**, **d3_d4** - X–M–X angles labeled according to **II**, °;

* **d_average** – average M–X distance, Å.

* **delta_d** - mean quadratic elongation ${\Delta}d$:

${\Delta}d=\frac{1}{6}\displaystyle\sum_{i=1}^{6}\left(\frac{d_{i}-\bar{d}}{\bar{d}}\right)^{2}$

where $d$ is individual M-X distance, $\bar{d}$ is the average M–X distance;

* **sigma_2** - angle variance $\sigma^{2}$:

 $\sigma^{2}=\frac{1}{11}\displaystyle\sum_{i=1}^{12}\left(\alpha_{i}-90\right)^{2}$
 
where $\alpha$ is individual <i>cis</i>-angle X-M-X;

* **X...X contacts** – space-separated string of X···X contacts distances (≤ 2·r<sub>VdW</sub>(X) + 1 Å) originated from one octahedron;

* **WdV contacts** – space-separated string of X···X contacts distances that equal or less than sum of van der Waals radii;

* **N_XX** – the number of X···X contacts (≤ 2·r<sub>VdW</sub>(X) + 1 Å) originated form one \[MX<sub>6</sub>\] octahedron;

* **N_VdW** – the number of van der Waals X···X contacts originated form one \[MX<sub>6</sub>\] octahedron;

* **XX_min** – minimal distance between halogen atom in neighboring chin anions;

* **X_average** – average X···X contact distance (≤ 2·r<sub>VdW</sub>(X) + 1 Å) originated form one \[MX<sub>6</sub>\] octahedron;

* **VdW_average** – average length of van der Waals X···X contacts originated form one \[MX<sub>6</sub>\] octahedron;

* **Type of bandgap** - bandgap type: **direct**, **indirect**, **XCCT** (charge transfer from halometallate anion to Cation), *CC* (Cation centrated);

* **Bandgap** - band gap value, eV;

* **Bandgap estimation comments** – comments to correctness of band gap estimation; not empty for incorrect determination.

In [6]:
# Information about data in columns (None null values, data type)
dataset.info(verbose=4, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Refcode                     239 non-null    str
 1   DOI                         238 non-null    str
 2   Authors                     239 non-null    str
 3   Journal                     239 non-null    str
 4   Journal year                239 non-null    int64
 5   Journal volume              220 non-null    float64
 6   Journal page or number      229 non-null    str
 7   Cation SMILES               239 non-null    str
 8   Cation substructure SMILES  239 non-null    str
 9   Space group                 239 non-null    str
 10  Int Tables number           239 non-null    int64
 11  Temperature                 238 non-null    float64
 12  a                           239 non-null    float64
 13  b                           239 non-null    float64
 14  c                           239 non-null    float64
 15  alpha                       239 non-null    float64
 16  beta                        239 non-null    float64
 17  gamma                       239 non-null    float64
 18  V                           239 non-null    float64
 19  Z                           239 non-null    int64
 20  R factor                    239 non-null    float64
 21  MX4 type                    239 non-null    str
 22  M                           239 non-null    str
 23  X                           239 non-null    str
 24  X_t1                        209 non-null    float64
 25  X_t2                        209 non-null    float64
 26  X_d1                        209 non-null    float64
 27  X_d2                        209 non-null    float64
 28  X_d3                        209 non-null    float64
 29  X_d4                        209 non-null    float64
 30  t1_t2                       209 non-null    float64
 31  t1_d1                       209 non-null    float64
 32  t1_d2                       209 non-null    float64
 33  t1_d3                       209 non-null    float64
 34  t1_d4                       209 non-null    float64
 35  t2_d1                       209 non-null    float64
 36  t2_d2                       209 non-null    float64
 37  t2_d3                       209 non-null    float64
 38  t2_d4                       209 non-null    float64
 39  d1_d2                       209 non-null    float64
 40  d1_d3                       209 non-null    float64
 41  d1_d4                       209 non-null    float64
 42  d2_d3                       209 non-null    float64
 43  d2_d4                       209 non-null    float64
 44  d3_d4                       209 non-null    float64
 45  d_average                   209 non-null    float64
 46  delta_d                     209 non-null    float64
 47  sigma_2                     209 non-null    float64
 48  X...X contacts              209 non-null    str
 49  VdW contacts                109 non-null    str
 50  N_XX                        209 non-null    float64
 51  N_VdW                       209 non-null    float64
 52  XX_min                      209 non-null    float64
 53  XX_average                  209 non-null    float64
 54  VdW_average                 209 non-null    float64
 55  Type of bandgap             115 non-null    str
 56  Bandgap                     129 non-null    float64
 57  Bangap estimation comments  5 non-null      str
dtypes: float64(40), int64(3), str(15)
memory usage: 108.4 KB

In [7]:
print(f'''Dataset contains the {dataset.shape[0]} object (crystal structures) that correspond to {len(set([x[:6] for x in dataset['Refcode']]))-1} different compounds (structures of some compounds are determined at different temperatures or by different scientific groups).

Bandgap values experimental determine for {sum(dataset["Bandgap"].notna())} objects.

For {sum(dataset["MX4 type"]=="no data")} structures there are no atomic coordinates in the CIF-file, it is impossible to calculate descriptors. For {dataset[(dataset["MX4 type"]=="no data")&(dataset["Bandgap"].notna())].shape[0]} of them Band gap value is known.

There are {sum(dataset["MX4 type"]=="beta")} structures with β-type anion and {sum(dataset["MX4 type"]=="gamma")} structures with γ-type anion and. Our are not able to describe them.

Thus for bandgap prediction {dataset[(dataset["MX4 type"]=="alpha")&(dataset["Bandgap"].notna())].shape[0]} potential objects remain.

For establishing relationships between "cation-structure parameters" {sum(dataset["MX4 type"]=="alpha")} objects can be used.''')

Dataset contains the 239 object (crystal structures) that correspond to 166 different compounds (structures of some compounds are determined at different temperatures or by different scientific groups).

Bandgap values experimental determine for 129 objects.

For 25 structures there are no atomic coordinates in the CIF-file, it is impossible to calculate descriptors. For 8 of them Band gap value is known.

There are 2 structures with β-type anion and 3 structures with γ-type anion and. Our are not able to describe them.

Thus for bandgap prediction 118 potential objects remain.

For establishing relationships between "cation-structure parameters" 209 objects can be used.

### I. Isomerism of \{MX<sub>4</sub>\}<sup>–</sup> anions

There are three types of anions \{MX<sub>4</sub>\}<sup>–</sup> in the Dataset. They all consist of octahedra, which are shared with each other by a common <i>cis</i>-edge. A different mutual orientations of octahedra along the chain are observed:

<div>
<img src="../images/mx4_anionic_chain_types.png" width="1200" />
</div>

### II. Anion geometry

Atomic labeling scheme for <i>α</i>-{MX<sub>4</sub>}<sup>–</sup> anion:


<div>
<img src="../images/mx6_labeling_scheme.png" width="600" aligne="center"/>
</div>

In [8]:
# Composition contingency table in all dataset
pair_counts_df(dataset, 'M', 'X').to_excel(os.path.join(path_to_table, 'dataset_composition_crosstab.xlsx'))
pair_counts_df(dataset, 'M', 'X')

X        I  Br I  Br  Cl Br  Cl  Sum
M
Bi      81     1  21      0  26  129
Bi Sb    1     1   0      0   0    2
Sb      23     1  29      4  51  108
Sum    105     3  50      4  77  239

In [9]:
# Band gap type counts
for i in dataset[(dataset['Type of bandgap'].isna())&(dataset['Bandgap'].notna())].index:
    dataset.loc[i, 'Type of bandgap'] = 'unk'
dataset['Type of bandgap'].value_counts()

Type of bandgap
direct      86
indirect    20
unk         16
XCCT         8
CC           1
Name: count, dtype: int64

***

## 2. Data analysis

In [10]:
# Curated Set construction (ctructures with only anionic alpha-type, inoraganic-associated correct determinated band gap)
curated_set = dataset.copy()
curated_set.drop(index=curated_set[(curated_set['MX4 type']!='alpha')|(curated_set['Type of bandgap']=='CC')|(curated_set['Type of bandgap']=='XCCT')|(curated_set['Bangap estimation comments'].notna())].index, inplace=True)
curated_set.index = range(curated_set.shape[0])

In [11]:
# Information about data in columns (None null values, data type)
curated_set.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Refcode                     195 non-null    str
 1   DOI                         194 non-null    str
 2   Authors                     195 non-null    str
 3   Journal                     195 non-null    str
 4   Journal year                195 non-null    int64
 5   Journal volume              182 non-null    float64
 6   Journal page or number      188 non-null    str
 7   Cation SMILES               195 non-null    str
 8   Cation substructure SMILES  195 non-null    str
 9   Space group                 195 non-null    str
 10  Int Tables number           195 non-null    int64
 11  Temperature                 194 non-null    float64
 12  a                           195 non-null    float64
 13  b                           195 non-null    float64
 14  c                           195 non-null    float64
 15  alpha                       195 non-null    float64
 16  beta                        195 non-null    float64
 17  gamma                       195 non-null    float64
 18  V                           195 non-null    float64
 19  Z                           195 non-null    int64
 20  R factor                    195 non-null    float64
 21  MX4 type                    195 non-null    str
 22  M                           195 non-null    str
 23  X                           195 non-null    str
 24  X_t1                        195 non-null    float64
 25  X_t2                        195 non-null    float64
 26  X_d1                        195 non-null    float64
 27  X_d2                        195 non-null    float64
 28  X_d3                        195 non-null    float64
 29  X_d4                        195 non-null    float64
 30  t1_t2                       195 non-null    float64
 31  t1_d1                       195 non-null    float64
 32  t1_d2                       195 non-null    float64
 33  t1_d3                       195 non-null    float64
 34  t1_d4                       195 non-null    float64
 35  t2_d1                       195 non-null    float64
 36  t2_d2                       195 non-null    float64
 37  t2_d3                       195 non-null    float64
 38  t2_d4                       195 non-null    float64
 39  d1_d2                       195 non-null    float64
 40  d1_d3                       195 non-null    float64
 41  d1_d4                       195 non-null    float64
 42  d2_d3                       195 non-null    float64
 43  d2_d4                       195 non-null    float64
 44  d3_d4                       195 non-null    float64
 45  d_average                   195 non-null    float64
 46  delta_d                     195 non-null    float64
 47  sigma_2                     195 non-null    float64
 48  X...X contacts              195 non-null    str
 49  VdW contacts                102 non-null    str
 50  N_XX                        195 non-null    float64
 51  N_VdW                       195 non-null    float64
 52  XX_min                      195 non-null    float64
 53  XX_average                  195 non-null    float64
 54  VdW_average                 195 non-null    float64
 55  Type of bandgap             106 non-null    str
 56  Bandgap                     105 non-null    float64
 57  Bangap estimation comments  0 non-null      str
dtypes: float64(40), int64(3), str(15)
memory usage: 88.5 KB

Сначала мы определили количество соединений с разным химическим составом: для всех соединений и для соединений с измеренным значением ШЗЗ. Ввод в виде таблицы:

In [12]:
count_all = pair_counts_df(curated_set, 'M', 'X')
count_with_bg = pair_counts_df(curated_set[curated_set['Bandgap'].notna()], 'M', 'X')

In [13]:
# All stuctures 
print(count_all)

X       I  Br I  Br  Cl Br  Cl  Sum
M
Bi     69     1  18      0  23  111
Bi Sb   1     1   0      0   0    2
Sb     21     1  20      1  39   82
Sum    91     3  38      1  62  195

In [14]:
# structures with determined band gap
print(count_with_bg)

X       I  Br I  Br  Cl  Sum
M
Bi     51     1   7   2   61
Bi Sb   1     1   0   0    2
Sb     18     1  15   8   42
Sum    70     3  22  10  105

In [15]:
# Save data
count_with_bg.to_excel(os.path.join(path_to_table, 'curatedset_composition_crosstab.xlsx'))

In [16]:
# Removing objects without band gap values
curated_set.drop(index=curated_set[curated_set['Bandgap'].isna()].index, inplace=True)
curated_set.index = range(curated_set.shape[0])

In [17]:
fig_1 = double_histograms_by_composition(curated_set.replace({'Bi Sb': 'Bi + Sb', 'Br I': 'Br + I'}))
fig_1.show()
fig_1.write_html(os.path.join(path_to_image, 'curatedset_bandgap_hisctogram.html'))
fig_1.write_image(os.path.join(path_to_image, 'curatedset_bandgap_hisctogram.png'), scale=10)

In [18]:
# Removing of non numbering columns
data = curated_set.copy()
composition_aid = data[['M', 'X']].copy()
data.drop(columns=data.columns[1:11].to_list()+data.columns[12:24].to_list()+['X...X contacts', 'VdW contacts', 'Type of bandgap', 'Bangap estimation comments', 'Type of bandgap', 'Bangap estimation comments'], inplace=True)

In [19]:
# Descriptors statistic
data.describe().to_excel(os.path.join(path_to_table, 'descriptors_statistic.xlsx'))
data.describe().round(4)

,Temperature,X_t1,X_t2,X_d1,X_d2,X_d3,X_d4,t1_t2,t1_d1,t1_d2,...,d3_d4,d_average,delta_d,sigma_2,N_XX,N_VdW,XX_min,XX_average,VdW_average,Bandgap
count,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,...,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000,105.0000
mean,227.6183,2.7810,2.8103,3.1998,2.9975,3.2832,2.9707,94.5260,89.5003,92.9927,...,85.6074,3.0071,0.0049,23.2000,5.5857,2.1457,3.9340,4.1731,3.9574,2.3068
std,85.6134,0.1787,0.1775,0.0953,0.1515,0.0872,0.1541,2.1247,2.3268,3.0200,...,4.1763,0.1182,0.0047,26.3391,2.1252,1.9633,0.2544,0.2184,0.2443,0.4767
min,85.0000,2.3587,2.3807,2.9069,2.4469,2.9872,2.4927,88.9620,83.7550,84.3880,...,65.3300,2.7126,0.0010,3.8500,0.5000,0.0000,3.2634,3.6944,3.4305,1.6700
25%,150.0000,2.6428,2.6762,3.1371,2.9401,3.2510,2.8787,93.2420,87.7660,91.3780,...,85.0990,2.8913,0.0022,11.0706,4.0000,0.0000,3.7961,4.0010,3.8101,1.9800
50%,293.0000,2.8400,2.9012,3.2219,3.0630,3.2824,3.0361,94.2980,89.6100,93.5890,...,86.4130,3.0716,0.0031,17.7957,6.0000,2.0000,3.9104,4.1533,3.9368,2.1300
75%,295.0000,2.9174,2.9419,3.2630,3.0931,3.3098,3.0845,95.8200,90.8420,95.1880,...,87.7120,3.0954,0.0048,23.8215,7.0000,4.0000,4.0386,4.3351,4.0600,2.6100
max,393.0200,2.9857,3.0662,3.3547,3.1947,3.5914,3.1567,102.2520,94.8640,99.6240,...,90.9930,3.1351,0.0244,154.6780,12.0000,8.0000,4.6949,4.6949,4.6949,3.5700

In [20]:
fig_3 = descriptor_violin_plot(dataframe=data)
fig_3.show()
fig_3.write_html(os.path.join(path_to_image, 'descriptor_distribution.html'))
fig_3.write_image(os.path.join(path_to_image, 'descriptor_distribution.png'), scale=10)

In [21]:
# Correlation analysis of dataset
corr_map = build_corr_map(data[data.columns[1:]])

# Visualization of correlation map 
fig_4 = heatmap_plot(corr_map, layout_params=dict(title=None))
fig_4.show()
fig_4.write_html(os.path.join(path_to_image, 'descriptor_heatmap.html'))
fig_4.write_image(os.path.join(path_to_image, 'descriptor_heatmap.png'), scale=10)

# # For publication version
# fig_4 = heatmap_plot(corr_map, traces_params=dict(textfont=dict(size=10, weight='bold'), texttemplate='%{z:.3f}'), layout_params=dict(title=None)) # For publication version
# fig_4.show()
# fig_4.write_image(os.path.join(path_to_image, 'descriptors_heatmap_publication_version.png'), scale=10)

In [22]:
fig_5 = descriptor_pairwise(dataframe=data, composition_aid=composition_aid, feature_names=['delta_d', 'sigma_2', 'd_average', 'N_XX', 'XX_average', 'X_t1', 'X_d4', 'd1_d3', 'd3_d4', 'Bandgap'])
fig_5.show()
fig_5.write_html(os.path.join(path_to_image, 'descriptor_pairwises.html'))
fig_5.write_image(os.path.join(path_to_image, 'descriptor_pairwises.png'), scale=2)

In [23]:
fig_6 = mx_correlation_plot(data=dataset, error_str=['BEXNOL']) # error_str corresponds to structures with incorrect X-ray diffraction experiment/refinement
fig_6.show()
fig_6.write_html(os.path.join(path_to_image, 'm-x_pairwise.html'))
fig_6.write_image(os.path.join(path_to_image, 'm-x_pairwise.png'), scale=10)

***

## 3. Prepare for ML development

In [24]:
# Generate d(X···X)/2·rVsW(X) desciptors
data['XXmin_2r'] = (data['XX_min']/composition_aid['X'].replace({'I': 4.2, 'Br I': (4.2+3.7)/2, 'Br': 3.7, 'Cl': 3.6})).astype(np.float64)
data['XXaver_2r'] = (data['XX_average']/composition_aid['X'].replace({'I': 4.2, 'Br I': (4.2+3.7)/2, 'Br': 3.7, 'Cl': 3.6})).astype(np.float64)
data['VdW_2r'] = (data['VdW_average']/composition_aid['X'].replace({'I': 4.2, 'Br I': (4.2+3.7)/2, 'Br': 3.7, 'Cl': 3.6})).astype(np.float64)
data = data[data.columns[:-4].to_list() + data.columns[-3:].to_list()+['Bandgap']]
# Generate composition descriptors
data['Composition'] = composition_aid['M'] + '_' + composition_aid['X']
data['M'] = data['Composition'].apply(lambda x: {'Bi': 0, 'Bi Sb': 0.5, 'Sb': 1}[x.split('_')[0]])
data['I'] = data['Composition'].apply(lambda x: {'I': 1, 'Br I': 0.5, 'Br': 0, 'Cl': 0}[x.split('_')[1]]) 
data['Br'] = data['Composition'].apply(lambda x: {'I': 0, 'Br I': 0.5, 'Br': 1, 'Cl': 0}[x.split('_')[1]])
data['Cl'] = data['Composition'].apply(lambda x: {'I': 0, 'Br I': 0, 'Br': 0, 'Cl': 1}[x.split('_')[1]])
data = data[['Refcode', 'Composition'] + data.columns[1:-6].to_list()+['M', 'I', 'Br', 'Cl', 'Bandgap']]

In [25]:
data.to_csv(os.path.join(path_to_data, 'task.csv'))
data.to_excel(os.path.join(path_to_data, 'task.xlsx'))

In [26]:
# Pearson correlation coefficients
p1, p2 = np.corrcoef(data['Bandgap'], data['delta_d'])[0, 1], np.corrcoef(data['Bandgap'], data['XXaver_2r'])[0, 1]

In [27]:
fig_7 = descriptors_vs_bandgap(dataframe=data, feature_1='delta_d', feature_2='XXaver_2r', composition_aid=composition_aid, subplot_titles=[f'<i>ρ<sub>P</sub></i> = {round(p1, 4)}<br> ', f'<i>ρ<sub>P</sub></i> = {round(p2, 4)}<br> '])
fig_7.show()
fig_7.write_html(os.path.join(path_to_image, 'descriptors_vs_band_gap.html'))
fig_7.write_image(os.path.join(path_to_image, 'descriptors_vs_band_gap.png'), scale=10)

***